apiVersion: v1
kind: Namespace
metadata:
  name: database-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: database-system
spec:
  selector:
    matchLabels:
      app: database
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: database
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 60
      containers:
        - name: mysql
          image: mysql:8
          resources:
            limits:
              cpu: "1000m" # Up to 1 full core
            requests:
              cpu: "1000m" # Use 1 full core
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: db_password
                  name: app-config
          ports:
            - name: mysql
              containerPort: 3306
          livenessProbe:
            exec:
              command: [ "mysqladmin", "ping" ]
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command: [ "mysql", "-h", "127.0.0.1", "-e", "SELECT 1" ]
            initialDelaySeconds: 5
            periodSeconds: 2
            timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: database-system
spec:
  type: ClusterIP
  selector:
    app: database
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql